### ISSUE TITLE
Add syncing network to actions table and use to add syncing network support in indexer-cli commands

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#1026]
### Background
Often subgraph deployments can be effectively grouped using the syncing network, so it would be useful for indexers to be able to use that field when defining and executing allocation strategy.

## Todo
- [ ] Add syncing_network to the Actions and IndexingRules tables
- [ ] Update indexer-cli commands to use syncing_network for additional control:
    - [ ] `graph indexer actions update ...` should support a --syncing-network filter parameter
    - [ ] `graph indexer actions approve ...` should support a --syncing-network filter parameter
    - [ ] `graph indexer allocations get ...` should support a --syncing-network filter
    - [ ] `graph indexer rules get ..`  should support a --syncing-network filter (`indexer rules set..` likely won't need updating)
- [ ] Can we query the graph-node's supported networks in order to be more intelligent about not trying to allocate/sync deployments the graph-node isn't configured to support?
