### ISSUE TITLE
Add a deployment management mode configuration similar to allocation management mode

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#713]
## Background
Indexers may have other systems/tools for managing deployments, so we'd like to provide the option for turning off deployment management in the indexer-agent.

## Goal
Add feature to support different deployment management modes, so indexers can turn off deployment management. 
Ultimately we can work towards a setup very similar to the allocation management modes: `auto`, `manual` and `oversight` that will give indexers queue management control of deployment changes.  However, in the beginning we can keep it simple and just support `auto` and `manual` modes.  

## Tasks
- [x] Add a startup parameter, `deploymentManagement`, with supported options: `auto` and `manual`
- [x] Add a conditional checking this parameter that will skip reconciling deployments if mode = `manual`

**Comment by fordN** [comment]
## Background
Indexers may have other systems/tools for managing deployments, so we'd like to provide the option for turning off deployment management in the indexer-agent.

## Goal
Add feature to support different deployment management modes, so indexers can turn off deployment management. 
Ultimately we can work towards a setup very similar to the allocation management modes: `auto`, `manual` and `oversight` that will give indexers queue management control of deployment changes.  However, in the beginning we can keep it simple and just support `auto` and `manual` modes.  

## Tasks
- [ ] Add a startup parameter for deployment management mode with supported options: `auto` and `manual`
- [ ] Add a conditional checking this parameter that will skip reconciling deployments if mode = `manual`
