### ISSUE TITLE
Enhancement: Indexer agent relies on graph-node to assign deployments to index-nodes

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#853]
Let's remove the naive indexer-agent deployment assignment algorithm and instead relying on the configurable graph-node deployment rule. 

```[tasklist]
### Tasks
- [ ] Indexer-agent use new pausing mechanism (depends on https://github.com/graphprotocol/graph-node/issues/5180)
- [ ] https://github.com/graphprotocol/indexer/issues/854
- [ ] test new process in local environment
```
